### ISSUE TITLE
StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by drenda** [tdelenikas/smslib#14]
I've a strange error happened during the parse of a PDU, I attach the stack trace and some logs.

The line 99 of MessageReader corrispond to:
int memIndex = Integer.parseInt(line.substring(i + 1, j).trim());

```
21/10/2015 11:50:03,754 DEBUG Thread-27 AbstractModemDriver:85-/dev/ttyUSB0:115200 <== AT+CPMS="SM"
21/10/2015 11:50:04,588 DEBUG Thread-27 AbstractModemDriver:129-/dev/ttyUSB0:115200 >>> 
21/10/2015 11:50:04,589 DEBUG Thread-27 AbstractModemDriver:129-/dev/ttyUSB0:115200 >>> +CPMS: 0,30,0,30
21/10/2015 11:50:04,590 DEBUG Thread-27 AbstractModemDriver:129-/dev/ttyUSB0:115200 >>> 
21/10/2015 11:50:04,591 DEBUG Thread-27 AbstractModemDriver:129-/dev/ttyUSB0:115200 >>> OK
21/10/2015 11:50:04,592 DEBUG Thread-27 AbstractModemDriver:183-/dev/ttyUSB0:115200 ==> +CPMS: 0,30,0,30$
21/10/2015 11:50:04,593 DEBUG Thread-27 AbstractModemDriver:85-/dev/ttyUSB0:115200 <== AT+CMGL=4
21/10/2015 11:50:05,395 DEBUG Thread-27 AbstractModemDriver:129-/dev/ttyUSB0:115200 >>> 
21/10/2015 11:50:05,397 DEBUG Thread-27 AbstractModemDriver:129-/dev/ttyUSB0:115200 >>> +CREG: 1
21/10/2015 11:50:05,398 DEBUG Thread-27 AbstractModemDriver:129-/dev/ttyUSB0:115200 >>> 
21/10/2015 11:50:05,399 DEBUG Thread-27 AbstractModemDriver:129-/dev/ttyUSB0:115200 >>> OK
21/10/2015 11:50:05,400 DEBUG Thread-27 AbstractModemDriver:183-/dev/ttyUSB0:115200 ==> +CREG: 1$
21/10/2015 11:50:05,401 ERROR Thread-27 MessageReader:76-Unhandled exception!
java.lang.StringIndexOutOfBoundsException: String index out of range: -7
    at java.lang.String.substring(String.java:1954) ~[?:1.8.0_33]
    at org.smslib.gateway.modem.MessageReader.parsePDU(MessageReader.java:99) ~[smslib-dev-SNAPSHOT.jar!/:?]
    at org.smslib.gateway.modem.MessageReader.run(MessageReader.java:67) [smslib-dev-SNAPSHOT.jar!/:?]
21/10/2015 11:50:20,403 DEBUG Thread-27 AbstractModemDriver:85-/dev/ttyUSB0:115200 <== AT+CPMS="SM"
21/10/2015 11:50:21,238 DEBUG Thread-27 AbstractModemDriver:129-/dev/ttyUSB0:115200 >>> 
21/10/2015 11:50:21,240 DEBUG Thread-27 AbstractModemDriver:129-/dev/ttyUSB0:115200 >>> +CPMS: 0,30,0,30
21/10/2015 11:50:21,242 DEBUG Thread-27 AbstractModemDriver:129-/dev/ttyUSB0:115200 >>> 
21/10/2015 11:50:21,243 DEBUG Thread-27 AbstractModemDriver:129-/dev/ttyUSB0:115200 >>> OK
21/10/2015 11:50:21,245 DEBUG Thread-27 AbstractModemDriver:183-/dev/ttyUSB0:115200 ==> +CPMS: 0,30,0,30$
21/10/2015 11:50:21,246 DEBUG Thread-27 AbstractModemDriver:85-/dev/ttyUSB0:115200 <== AT+CMGL=4
21/10/2015 11:50:22,050 DEBUG Thread-27 AbstractModemDriver:129-/dev/ttyUSB0:115200 >>> 
21/10/2015 11:50:22,052 DEBUG Thread-27 AbstractModemDriver:129-/dev/ttyUSB0:115200 >>> OK
21/10/2015 11:50:22,054 DEBUG Thread-27 AbstractModemDriver:183-/dev/ttyUSB0:115200 ==> 
21/10/2015 11:50:37,055 DEBUG Thread-27 AbstractModemDriver:85-/dev/ttyUSB0:115200 <== AT+CPMS="SM"
21/10/2015 11:50:37,890 DEBUG Thread-27 AbstractModemDriver:129-/dev/ttyUSB0:115200 >>> 
21/10/2015 11:50:37,892 DEBUG Thread-27 AbstractModemDriver:129-/dev/ttyUSB0:115200 >>> +CPMS: 0,30,0,30
21/10/2015 11:50:37,894 DEBUG Thread-27 AbstractModemDriver:129-/dev/ttyUSB0:115200 >>> 
21/10/2015 11:50:37,896 DEBUG Thread-27 AbstractModemDriver:129-/dev/ttyUSB0:115200 >>> OK
21/10/2015 11:50:37,897 DEBUG Thread-27 AbstractModemDriver:183-/dev/ttyUSB0:115200 ==> +CPMS: 0,30,0,30$
21/10/2015 11:50:37,898 DEBUG Thread-27 AbstractModemDriver:85-/dev/ttyUSB0:115200 <== AT+CMGL=4
21/10/2015 11:50:38,702 DEBUG Thread-27 AbstractModemDriver:129-/dev/ttyUSB0:115200 >>> 
21/10/2015 11:50:38,704 DEBUG Thread-27 AbstractModemDriver:129-/dev/ttyUSB0:115200 >>> OK
21/10/2015 11:50:38,706 DEBUG Thread-27 AbstractModemDriver:183-/dev/ttyUSB0:115200 ==> 
21/10/2015 11:50:53,708 DEBUG Thread-27 AbstractModemDriver:85-/dev/ttyUSB0:115200 <== AT+CPMS="SM"
21/10/2015 11:50:54,543 DEBUG Thread-27 AbstractModemDriver:129-/dev/ttyUSB0:115200 >>> 
21/10/2015 11:50:54,545 DEBUG Thread-27 AbstractModemDriver:129-/dev/ttyUSB0:115200 >>> +CPMS: 0,30,0,30
21/10/2015 11:50:54,546 DEBUG Thread-27 AbstractModemDriver:129-/dev/ttyUSB0:115200 >>> 
21/10/2015 11:50:54,548 DEBUG Thread-27 AbstractModemDriver:129-/dev/ttyUSB0:115200 >>> OK
21/10/2015 11:50:54,549 DEBUG Thread-27 AbstractModemDriver:183-/dev/ttyUSB0:115200 ==> +CPMS: 0,30,0,30$
21/10/2015 11:50:54,551 DEBUG Thread-27 AbstractModemDriver:85-/dev/ttyUSB0:115200 <== AT+CMGL=4
21/10/2015 11:50:55,355 DEBUG Thread-27 AbstractModemDriver:129-/dev/ttyUSB0:115200 >>> 
21/10/2015 11:50:55,357 DEBUG Thread-27 AbstractModemDriver:129-/dev/ttyUSB0:115200 >>> OK
21/10/2015 11:50:55,358 DEBUG Thread-27 AbstractModemDriver:183-/dev/ttyUSB0:115200 ==> 
21/10/2015 11:51:10,360 DEBUG Thread-27 AbstractModemDriver:85-/dev/ttyUSB0:115200 <== AT+CPMS="SM"
21/10/2015 11:51:11,195 DEBUG Thread-27 AbstractModemDriver:129-/dev/ttyUSB0:115200 >>> 
21/10/2015 11:51:11,197 DEBUG Thread-27 AbstractModemDriver:129-/dev/ttyUSB0:115200 >>> +CPMS: 0,30,0,30
21/10/2015 11:51:11,199 DEBUG Thread-27 AbstractModemDriver:129-/dev/ttyUSB0:115200 >>> 
21/10/2015 11:51:11,200 DEBUG Thread-27 AbstractModemDriver:129-/dev/ttyUSB0:115200 >>> OK
21/10/2015 11:51:11,202 DEBUG Thread-27 AbstractModemDriver:183-/dev/ttyUSB0:115200 ==> +CPMS: 0,30,0,30$
21/10/2015 11:51:11,203 DEBUG Thread-27 AbstractModemDriver:85-/dev/ttyUSB0:115200 <== AT+CMGL=4
21/10/2015 11:51:12,007 DEBUG Thread-27 AbstractModemDriver:129-/dev/ttyUSB0:115200 >>> 
21/10/2015 11:51:12,009 DEBUG Thread-27 AbstractModemDriver:129-/dev/ttyUSB0:115200 >>> OK
21/10/2015 11:51:12,011 DEBUG Thread-27 AbstractModemDriver:183-/dev/ttyUSB0:115200 ==> 
21/10/2015 11:51:27,013 DEBUG Thread-27 AbstractModemDriver:85-/dev/ttyUSB0:115200 <== AT+CPMS="SM"
21/10/2015 11:51:27,848 DEBUG Thread-27 AbstractModemDriver:129-/dev/ttyUSB0:115200 >>> 
21/10/2015 11:51:27,850 DEBUG Thread-27 AbstractModemDriver:129-/dev/ttyUSB0:115200 >>> +CPMS: 0,30,0,30
21/10/2015 11:51:27,852 DEBUG Thread-27 AbstractModemDriver:129-/dev/ttyUSB0:115200 >>> 
21/10/2015 11:51:27,853 DEBUG Thread-27 AbstractModemDriver:129-/dev/ttyUSB0:115200 >>> OK
21/10/2015 11:51:27,855 DEBUG Thread-27 AbstractModemDriver:183-/dev/ttyUSB0:115200 ==> +CPMS: 0,30,0,30$
21/10/2015 11:51:27,856 DEBUG Thread-27 AbstractModemDriver:85-/dev/ttyUSB0:115200 <== AT+CMGL=4
21/10/2015 11:51:28,660 DEBUG Thread-27 AbstractModemDriver:129-/dev/ttyUSB0:115200 >>> 
21/10/2015 11:51:28,663 DEBUG Thread-27 AbstractModemDriver:129-/dev/ttyUSB0:115200 >>> OK
21/10/2015 11:51:28,665 DEBUG Thread-27 AbstractModemDriver:183-/dev/ttyUSB0:115200 ==> 
21/10/2015 11:51:43,667 DEBUG Thread-27 AbstractModemDriver:85-/dev/ttyUSB0:115200 <== AT+CPMS="SM"
21/10/2015 11:51:44,502 DEBUG Thread-27 AbstractModemDriver:129-/dev/ttyUSB0:115200 >>> 
21/10/2015 11:51:44,504 DEBUG Thread-27 AbstractModemDriver:129-/dev/ttyUSB0:115200 >>> +CPMS: 0,30,0,30
21/10/2015 11:51:44,506 DEBUG Thread-27 AbstractModemDriver:129-/dev/ttyUSB0:115200 >>> 
21/10/2015 11:51:44,507 DEBUG Thread-27 AbstractModemDriver:129-/dev/ttyUSB0:115200 >>> OK
21/10/2015 11:51:44,509 DEBUG Thread-27 AbstractModemDriver:183-/dev/ttyUSB0:115200 ==> +CPMS: 0,30,0,30$
21/10/2015 11:51:44,510 DEBUG Thread-27 AbstractModemDriver:85-/dev/ttyUSB0:115200 <== AT+CMGL=4
21/10/2015 11:51:45,314 DEBUG Thread-27 AbstractModemDriver:129-/dev/ttyUSB0:115200 >>> 
21/10/2015 11:51:45,316 DEBUG Thread-27 AbstractModemDriver:129-/dev/ttyUSB0:115200 >>> OK
21/10/2015 11:51:45,318 DEBUG Thread-27 AbstractModemDriver:183-/dev/ttyUSB0:115200 ==> 
21/10/2015 11:52:00,319 DEBUG Thread-27 AbstractModemDriver:85-/dev/ttyUSB0:115200 <== AT+CPMS="SM"
21/10/2015 11:52:01,154 DEBUG Thread-27 AbstractModemDriver:129-/dev/ttyUSB0:115200 >>> 
21/10/2015 11:52:01,156 DEBUG Thread-27 AbstractModemDriver:129-/dev/ttyUSB0:115200 >>> +CREG: 2
21/10/2015 11:52:01,157 DEBUG Thread-27 AbstractModemDriver:129-/dev/ttyUSB0:115200 >>> 
21/10/2015 11:52:01,159 DEBUG Thread-27 AbstractModemDriver:129-/dev/ttyUSB0:115200 >>> +CREG: 1
21/10/2015 11:52:01,160 DEBUG Thread-27 AbstractModemDriver:129-/dev/ttyUSB0:115200 >>> 
21/10/2015 11:52:01,162 DEBUG Thread-27 AbstractModemDriver:129-/dev/ttyUSB0:115200 >>> +CPMS: 0,30,0,30
21/10/2015 11:52:01,163 DEBUG Thread-27 AbstractModemDriver:129-/dev/ttyUSB0:115200 >>> 
21/10/2015 11:52:01,165 DEBUG Thread-27 AbstractModemDriver:129-/dev/ttyUSB0:115200 >>> OK
21/10/2015 11:52:01,166 DEBUG Thread-27 AbstractModemDriver:183-/dev/ttyUSB0:115200 ==> +CREG: 2$+CREG: 1$+CPMS: 0,30,0,30$
21/10/2015 11:52:01,167 DEBUG Thread-27 AbstractModemDriver:85-/dev/ttyUSB0:115200 <== AT+CMGL=4
21/10/2015 11:52:01,971 DEBUG Thread-27 AbstractModemDriver:129-/dev/ttyUSB0:115200 >>> 
21/10/2015 11:52:01,973 DEBUG Thread-27 AbstractModemDriver:129-/dev/ttyUSB0:115200 >>> OK
21/10/2015 11:52:01,974 DEBUG Thread-27 AbstractModemDriver:183-/dev/ttyUSB0:115200 ==> 
```

**Comment by tdelenikas** [comment]
Do you still have the entire log? Can you send it to me (info@smslib.org)

**Comment by drenda** [comment]
Unfortunately not.

**Comment by tdelenikas** [comment]
If it happens again, please keep the entire log.
The error you see is generated from the reader thread which is not included in the log above.
