### ISSUE TITLE
please advice sample sql for gateway

### ISSUE THREAD

**Issue by ghost** [tdelenikas/smslib#16]
HI

I am using modem . DATABASE Dump is below
INSERT INTO `smslib_gateways` (`id`, `class`, `gateway_id`, `p0`, `p1`, `p2`, `p3`, `p4`, `p5`, `sender_address`, `priority`, `max_message_parts`, `delivery_reports`, `profile`, `enabled`) VALUES
(1, 'org.smslib.gateway.modem.Modem', 'COM30', 'com30', '115200', NULL, NULL, NULL, NULL, NULL, 0, 4, 0, '*', 1);

But I am getting exception. Please advise. 

107    2016-01-03 16:40:09,137 [Main Dispatcher] DEBUG org.smslib.threading.ServiceMessageDispatcher  - Started!
363    2016-01-03 16:40:09,393 [main] INFO  org.smslib.smsserver.SMSServer  - Registering gateway: COM30
2930   2016-01-03 16:40:11,960 [main] INFO  org.smslib.Service  - Registering Gateway: COM30 (GSM Modem) [com30:115200]
2930   2016-01-03 16:40:11,960 [main] INFO  org.smslib.Service  - Starting gateway: COM30
2931   2016-01-03 16:40:11,961 [main] INFO  org.smslib.gateway.AbstractGateway  - Starting gateway: COM30 (GSM Modem) [com30:115200]
2932   2016-01-03 16:40:11,962 [main] DEBUG org.smslib.gateway.modem.driver.SerialModemDriver  - Opening comm port: com30:115200
2939   2016-01-03 16:40:11,969 [main] INFO  org.smslib.gateway.modem.driver.serial.CommPortIdentifier  - Using 'javax.comm' serial library.
2942   2016-01-03 16:40:11,972 [main] ERROR org.smslib.gateway.AbstractGateway  - Unhandled Exception!
java.lang.RuntimeException: javax.comm.NoSuchPortException
    at org.smslib.gateway.modem.driver.serial.CommPortIdentifier.getPortIdentifier(CommPortIdentifier.java:199)
    at org.smslib.gateway.modem.driver.SerialModemDriver.openPort(SerialModemDriver.java:38)
    at org.smslib.gateway.modem.Modem._start(Modem.java:85)
    at org.smslib.gateway.AbstractGateway.start(AbstractGateway.java:176)
    at org.smslib.Service.registerGateway(Service.java:533)
    at org.smslib.smsserver.SMSServer.loadGatewayDefinitions(SMSServer.java:130)
    at org.smslib.smsserver.SMSServer.startup(SMSServer.java:95)
    at org.smslib.smsserver.SMSServer.main(SMSServer.java:198)
Caused by: javax.comm.NoSuchPortException
    at javax.comm.CommPortIdentifier.getPortIdentifier(CommPortIdentifier.java:105)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.smslib.gateway.modem.driver.serial.CommPortIdentifier.getPortIdentifier(CommPortIdentifier.java:195)
    ... 7 more
2946   2016-01-03 16:40:11,976 [main] WARN  org.smslib.Service  - Gateway COM30 did not start!

**Comment by tdelenikas** [comment]
Your issue must be `com30`.

I guess you are sure that there is a `com30` on your computer, right?
Try to set it in capital letters (i.e. `COM30`) - sometimes it does make a difference, especially if you work with a comm library _other than_ Java Comm v2.

**Comment by ghost** [comment]
I tried using COM30 but same port is working with Putty. however its failing here. Can you advise any way to debug modem ports. Or Scan all existing ports.

**Comment by tdelenikas** [comment]
Could it be that the javacomm library is not installed properly???
If your COM30 works with putty, it should work ok here as well.

Try running the smslib jar file by itself, i.e.

`java -jar smslib.jar`

It will try to scan all available / identified ports.

**Comment by ghost** [comment]
![image](https://cloud.githubusercontent.com/assets/6249191/12108982/5645902c-b3a3-11e5-8e70-79e65a29ac38.png)
Thanks , I got this solved  by reinstalling DLL RXTX files. I am getting these exceptions.  Is this modem specific or just bug ?

**Comment by ghost** [comment]
HI

Seems its some mysql column datatype mismatch issue. 

111501 2016-01-05 13:25:12,368 [Callback Manager Dispatcher] ERROR org.smslib.smsserver.db.MySQLDatabaseHandler  - Error!
java.lang.NullPointerException
    at java.math.BigInteger.stripLeadingZeroBytes(BigInteger.java:3995)
    at java.math.BigInteger.<init>(BigInteger.java:346)
    at org.smslib.helper.Common.bytesToString(Common.java:104)
    at org.smslib.smsserver.db.MySQLDatabaseHandler.saveInboundMessage(MySQLDatabaseHandler.java:206)
    at org.smslib.smsserver.callback.InboundMessageCallback.process(InboundMessageCallback.java:19)
    at org.smslib.threading.CallbackManager$CallbackManagerDispatcher.run(CallbackManager.java:240)

I have attached the log file too.

Rgds
Anshu

[smsserver.log.txt](https://github.com/smslib/smslib/files/78130/smsserver.log.txt)

**Comment by ghost** [comment]
I changed MODEM to WaveCOM Still the same challenge.
54357  2016-01-05 14:21:59,595 [Callback Manager Dispatcher] ERROR org.smslib.smsserver.callback.InboundMessageCallback  - Error!
java.lang.NullPointerException
    at java.math.BigInteger.stripLeadingZeroBytes(BigInteger.java:3995)
    at java.math.BigInteger.<init>(BigInteger.java:346)
    at org.smslib.helper.Common.bytesToString(Common.java:104)
    at org.smslib.smsserver.db.MySQLDatabaseHandler.saveInboundMessage(MySQLDatabaseHandler.java:206)
    at org.smslib.smsserver.callback.InboundMessageCallback.process(InboundMessageCallback.java:19)
    at org.smslib.threading.CallbackManager$CallbackManagerDispatcher.run(CallbackManager.java:240)
54405  2016-01-05 14:21:59,643 [Callback Manager Dispatcher] ERROR org.smslib.smsserver.db.MySQLDatabaseHandler  - Error!

[smsserver2.log.txt](https://github.com/smslib/smslib/files/78189/smsserver2.log.txt)

**Comment by tdelenikas** [comment]
You have some multipart 8bit messages (those coming from 55100) which do not get handled correctly... This is causing the trouble.
