### ISSUE TITLE
Neither Java Comm nor RXTX library found.

### ISSUE THREAD

**Issue by mtangoo** [tdelenikas/smslib#6]
I'm trying out smslib and cannot get it working. You see, I have followed Instructions on smslib site and did:
∘ sudo cp RXTXcomm.jar /usr/lib/jvm/java-7-oracle/jre/lib/ext/
∘ sudo cp librxtxSerial.so /usr/lib/jvm/java-7-oracle/jre/lib/amd64/
∘ sudo cp librxtxParallel.so /usr/lib/jvm/java-7-oracle/jre/lib/amd64/

Tried to run an example ans all i get is error below. I tried to delete these and install Ubuntu package `sudo apt-get install librxtx-java` with pretty same error.

Is there anything else I need to do? I use version 4 beta with Netbeans IDE, Ubuntu 13.10 Saucy.

Here is the error

```
Exception in thread "main" java.lang.ExceptionInInitializerError
    at org.smslib.gateway.modem.driver.SerialModemDriver.openPort(SerialModemDriver.java:38)
    at org.smslib.gateway.modem.Modem._start(Modem.java:85)
    at org.smslib.gateway.AbstractGateway.start(AbstractGateway.java:176)
    at org.smslib.Service.registerGateway(Service.java:531)
    at co.tz.hosannahighertech.ujumbe.Ujumbe.main(Ujumbe.java:40)
Caused by: java.lang.RuntimeException: Neither Java Comm nor RXTX library found. Please check http://smslib.org/doc/installation/#Java_Communications_Library
    at org.smslib.gateway.modem.driver.serial.CommPortIdentifier.<clinit>(CommPortIdentifier.java:63)
    ... 5 more
Java Result: 1

```

**Comment by tdelenikas** [comment]
I think that the .so files should go to **jre/bin** and not to jre/lib/amd64/.

Can you try once more?

**Comment by mtangoo** [comment]
Still the same problem. Do i need to restart a machine?

**Comment by mtangoo** [comment]
Am using [64 version](http://mfizz.com/oss/rxtx-for-java) of RXTX if that matter at all

**Comment by tdelenikas** [comment]
This error has more to do with `RXTXcomm.jar`. It seems like it's not found or something.
Are you sure you have **one** JRE directory?

**Comment by mtangoo** [comment]
I have single JDK java-7-oracle

**Comment by mtangoo** [comment]
Do I need to add `RXTXcomm.jar` to my netbeans project?

**Comment by tdelenikas** [comment]
Everything that goes into `lib/ext` is supposed to be "public" - but, try anyway...

**Comment by mtangoo** [comment]
Well now I have

```
java.lang.UnsatisfiedLinkError: no rxtxSerial in java.library.path thrown while loading gnu.io.RXTXCommDriver
Exception in thread "main" java.lang.UnsatisfiedLinkError: no rxtxSerial in java.library.path
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1886)
    at java.lang.Runtime.loadLibrary0(Runtime.java:849)
    at java.lang.System.loadLibrary(System.java:1088)
    at gnu.io.CommPortIdentifier.<clinit>(CommPortIdentifier.java:123)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:190)
    at org.smslib.gateway.modem.driver.serial.CommPortIdentifier.<clinit>(CommPortIdentifier.java:58)
    at org.smslib.gateway.modem.driver.SerialModemDriver.openPort(SerialModemDriver.java:38)
    at org.smslib.gateway.modem.Modem._start(Modem.java:85)
    at org.smslib.gateway.AbstractGateway.start(AbstractGateway.java:176)
    at org.smslib.Service.registerGateway(Service.java:531)
    at co.tz.hosannahighertech.ujumbe.Ujumbe.main(Ujumbe.java:40)
Java Result: 1
```

**Comment by tdelenikas** [comment]
Good!

This is described here: http://smslib.org/doc/v4/UsingGSMModems, check section 'Linux and unresolved references'.

**Comment by mtangoo** [comment]
Well Checking in netbeans it shows loaded JDK is `/usr/local/jdk1.7.0_45`
I have to check why is so and when did I Install that JDK!

**Comment by mtangoo** [comment]
found that hint [here](http://stackoverflow.com/questions/8197639/java-lang-unsatisfiedlinkerror-no-rxtxserial-in-java-library-path)

**Comment by mtangoo** [comment]
Well Though I get another error which I will append at the end of this comment, Its recognized now. All I did is to know that there is "mystical" JDK also installed. So I copied files as follows:
`sudo cp RXTXcomm.jar /usr/local/jdk1.7.0_45/jre/lib/ext/RXTXcomm.jar`
`cp librxtxSerial.so /usr/local/jdk1.7.0_45/jre/lib/amd64/`

And that was it. now I get 

```
RXTX fhs_lock() Error: creating lock file: /var/lock/LCK..ttyUSB2: File exists
RXTX fhs_lock() Error: creating lock file: /var/lock/LCK..ttyUSB2: File exists
RXTX fhs_lock() Error: creating lock file: /var/lock/LCK..ttyUSB2: File exists
```

Iam trying to fix it but its not as sinister as the first one.
Thanks alot :100:

**Comment by mtangoo** [comment]
Final issue is that its not sending using code below. I thought I should not open new ticket since this might be minor issue. here is essential part of code

``` java
// Start the service.
            Service.getInstance().start();
            // Define and register a modem.
            // TODO: Check the PINs and the SMSC number in the line below!
            Modem modemGateway = new Modem("modem", "/dev/ttyACM0", 19200, "1309", "", new MsIsdn("0717*****", Type.National), "");
            Service.getInstance().registerGateway(modemGateway);
            //Send sample SMS
             OutboundMessage message = new OutboundMessage("0754****", "Hello World!");
            Service.getInstance().send(message);
            Thread.sleep(30000);
            // Get rid of the gateway!
            Service.getInstance().unregisterGateway(modemGateway);
```
